// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigurationMessage.proto

package org.embox.robobot.proto;

public final class ConfigurationMessage {
  private ConfigurationMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code DeviceType}
   */
  public enum DeviceType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LEGO_NXT = 0;</code>
     */
    LEGO_NXT(0, 0),
    /**
     * <code>SIMULATOR = 1;</code>
     */
    SIMULATOR(1, 1),
    ;

    /**
     * <code>LEGO_NXT = 0;</code>
     */
    public static final int LEGO_NXT_VALUE = 0;
    /**
     * <code>SIMULATOR = 1;</code>
     */
    public static final int SIMULATOR_VALUE = 1;


    public final int getNumber() { return value; }

    public static DeviceType valueOf(int value) {
      switch (value) {
        case 0: return LEGO_NXT;
        case 1: return SIMULATOR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DeviceType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<DeviceType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DeviceType>() {
            public DeviceType findValueByNumber(int number) {
              return DeviceType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ConfigurationMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final DeviceType[] VALUES = values();

    public static DeviceType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private DeviceType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:DeviceType)
  }

  public interface DeviceConfigurationMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string id = 1;
    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    // required .DeviceType type = 2;
    /**
     * <code>required .DeviceType type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required .DeviceType type = 2;</code>
     */
    ConfigurationMessage.DeviceType getType();

    // required bytes sensors = 3;
    /**
     * <code>required bytes sensors = 3;</code>
     */
    boolean hasSensors();
    /**
     * <code>required bytes sensors = 3;</code>
     */
    com.google.protobuf.ByteString getSensors();

    // required bytes commands = 4;
    /**
     * <code>required bytes commands = 4;</code>
     */
    boolean hasCommands();
    /**
     * <code>required bytes commands = 4;</code>
     */
    com.google.protobuf.ByteString getCommands();
  }
  /**
   * Protobuf type {@code DeviceConfigurationMessage}
   */
  public static final class DeviceConfigurationMessage extends
      com.google.protobuf.GeneratedMessage
      implements DeviceConfigurationMessageOrBuilder {
    // Use DeviceConfigurationMessage.newBuilder() to construct.
    private DeviceConfigurationMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DeviceConfigurationMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DeviceConfigurationMessage defaultInstance;
    public static DeviceConfigurationMessage getDefaultInstance() {
      return defaultInstance;
    }

    public DeviceConfigurationMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DeviceConfigurationMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              ConfigurationMessage.DeviceType value = ConfigurationMessage.DeviceType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              sensors_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              commands_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ConfigurationMessage.internal_static_DeviceConfigurationMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ConfigurationMessage.internal_static_DeviceConfigurationMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ConfigurationMessage.DeviceConfigurationMessage.class, ConfigurationMessage.DeviceConfigurationMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<DeviceConfigurationMessage> PARSER =
        new com.google.protobuf.AbstractParser<DeviceConfigurationMessage>() {
      public DeviceConfigurationMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeviceConfigurationMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DeviceConfigurationMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .DeviceType type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private ConfigurationMessage.DeviceType type_;
    /**
     * <code>required .DeviceType type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .DeviceType type = 2;</code>
     */
    public ConfigurationMessage.DeviceType getType() {
      return type_;
    }

    // required bytes sensors = 3;
    public static final int SENSORS_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString sensors_;
    /**
     * <code>required bytes sensors = 3;</code>
     */
    public boolean hasSensors() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes sensors = 3;</code>
     */
    public com.google.protobuf.ByteString getSensors() {
      return sensors_;
    }

    // required bytes commands = 4;
    public static final int COMMANDS_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString commands_;
    /**
     * <code>required bytes commands = 4;</code>
     */
    public boolean hasCommands() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes commands = 4;</code>
     */
    public com.google.protobuf.ByteString getCommands() {
      return commands_;
    }

    private void initFields() {
      id_ = "";
      type_ = ConfigurationMessage.DeviceType.LEGO_NXT;
      sensors_ = com.google.protobuf.ByteString.EMPTY;
      commands_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSensors()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCommands()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, sensors_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, commands_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, sensors_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, commands_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ConfigurationMessage.DeviceConfigurationMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ConfigurationMessage.DeviceConfigurationMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ConfigurationMessage.DeviceConfigurationMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ConfigurationMessage.DeviceConfigurationMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ConfigurationMessage.DeviceConfigurationMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ConfigurationMessage.DeviceConfigurationMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ConfigurationMessage.DeviceConfigurationMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ConfigurationMessage.DeviceConfigurationMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ConfigurationMessage.DeviceConfigurationMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ConfigurationMessage.DeviceConfigurationMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ConfigurationMessage.DeviceConfigurationMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DeviceConfigurationMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ConfigurationMessage.DeviceConfigurationMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ConfigurationMessage.internal_static_DeviceConfigurationMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ConfigurationMessage.internal_static_DeviceConfigurationMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ConfigurationMessage.DeviceConfigurationMessage.class, ConfigurationMessage.DeviceConfigurationMessage.Builder.class);
      }

      // Construct using ConfigurationMessage.DeviceConfigurationMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = ConfigurationMessage.DeviceType.LEGO_NXT;
        bitField0_ = (bitField0_ & ~0x00000002);
        sensors_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        commands_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ConfigurationMessage.internal_static_DeviceConfigurationMessage_descriptor;
      }

      public ConfigurationMessage.DeviceConfigurationMessage getDefaultInstanceForType() {
        return ConfigurationMessage.DeviceConfigurationMessage.getDefaultInstance();
      }

      public ConfigurationMessage.DeviceConfigurationMessage build() {
        ConfigurationMessage.DeviceConfigurationMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ConfigurationMessage.DeviceConfigurationMessage buildPartial() {
        ConfigurationMessage.DeviceConfigurationMessage result = new ConfigurationMessage.DeviceConfigurationMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sensors_ = sensors_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.commands_ = commands_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ConfigurationMessage.DeviceConfigurationMessage) {
          return mergeFrom((ConfigurationMessage.DeviceConfigurationMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ConfigurationMessage.DeviceConfigurationMessage other) {
        if (other == ConfigurationMessage.DeviceConfigurationMessage.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasSensors()) {
          setSensors(other.getSensors());
        }
        if (other.hasCommands()) {
          setCommands(other.getCommands());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasSensors()) {
          
          return false;
        }
        if (!hasCommands()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ConfigurationMessage.DeviceConfigurationMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ConfigurationMessage.DeviceConfigurationMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string id = 1;
      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      // required .DeviceType type = 2;
      private ConfigurationMessage.DeviceType type_ = ConfigurationMessage.DeviceType.LEGO_NXT;
      /**
       * <code>required .DeviceType type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .DeviceType type = 2;</code>
       */
      public ConfigurationMessage.DeviceType getType() {
        return type_;
      }
      /**
       * <code>required .DeviceType type = 2;</code>
       */
      public Builder setType(ConfigurationMessage.DeviceType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .DeviceType type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = ConfigurationMessage.DeviceType.LEGO_NXT;
        onChanged();
        return this;
      }

      // required bytes sensors = 3;
      private com.google.protobuf.ByteString sensors_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes sensors = 3;</code>
       */
      public boolean hasSensors() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes sensors = 3;</code>
       */
      public com.google.protobuf.ByteString getSensors() {
        return sensors_;
      }
      /**
       * <code>required bytes sensors = 3;</code>
       */
      public Builder setSensors(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sensors_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes sensors = 3;</code>
       */
      public Builder clearSensors() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sensors_ = getDefaultInstance().getSensors();
        onChanged();
        return this;
      }

      // required bytes commands = 4;
      private com.google.protobuf.ByteString commands_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes commands = 4;</code>
       */
      public boolean hasCommands() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes commands = 4;</code>
       */
      public com.google.protobuf.ByteString getCommands() {
        return commands_;
      }
      /**
       * <code>required bytes commands = 4;</code>
       */
      public Builder setCommands(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        commands_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes commands = 4;</code>
       */
      public Builder clearCommands() {
        bitField0_ = (bitField0_ & ~0x00000008);
        commands_ = getDefaultInstance().getCommands();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DeviceConfigurationMessage)
    }

    static {
      defaultInstance = new DeviceConfigurationMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DeviceConfigurationMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_DeviceConfigurationMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DeviceConfigurationMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032ConfigurationMessage.proto\"f\n\032DeviceCo" +
      "nfigurationMessage\022\n\n\002id\030\001 \002(\t\022\031\n\004type\030\002" +
      " \002(\0162\013.DeviceType\022\017\n\007sensors\030\003 \002(\014\022\020\n\010co" +
      "mmands\030\004 \002(\014*)\n\nDeviceType\022\014\n\010LEGO_NXT\020\000" +
      "\022\r\n\tSIMULATOR\020\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_DeviceConfigurationMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_DeviceConfigurationMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_DeviceConfigurationMessage_descriptor,
              new java.lang.String[] { "Id", "Type", "Sensors", "Commands", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
