# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ConfigurationMessage.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ConfigurationMessage.proto',
  package='',
  serialized_pb='\n\x1a\x43onfigurationMessage.proto\"f\n\x1a\x44\x65viceConfigurationMessage\x12\n\n\x02id\x18\x01 \x02(\t\x12\x19\n\x04type\x18\x02 \x02(\x0e\x32\x0b.DeviceType\x12\x0f\n\x07sensors\x18\x03 \x02(\x0c\x12\x10\n\x08\x63ommands\x18\x04 \x02(\x0c*)\n\nDeviceType\x12\x0c\n\x08LEGO_NXT\x10\x00\x12\r\n\tSIMULATOR\x10\x01')

_DEVICETYPE = _descriptor.EnumDescriptor(
  name='DeviceType',
  full_name='DeviceType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LEGO_NXT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIMULATOR', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=134,
  serialized_end=175,
)

DeviceType = enum_type_wrapper.EnumTypeWrapper(_DEVICETYPE)
LEGO_NXT = 0
SIMULATOR = 1



_DEVICECONFIGURATIONMESSAGE = _descriptor.Descriptor(
  name='DeviceConfigurationMessage',
  full_name='DeviceConfigurationMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DeviceConfigurationMessage.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='DeviceConfigurationMessage.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sensors', full_name='DeviceConfigurationMessage.sensors', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='commands', full_name='DeviceConfigurationMessage.commands', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=30,
  serialized_end=132,
)

_DEVICECONFIGURATIONMESSAGE.fields_by_name['type'].enum_type = _DEVICETYPE
DESCRIPTOR.message_types_by_name['DeviceConfigurationMessage'] = _DEVICECONFIGURATIONMESSAGE

class DeviceConfigurationMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DEVICECONFIGURATIONMESSAGE

  # @@protoc_insertion_point(class_scope:DeviceConfigurationMessage)


# @@protoc_insertion_point(module_scope)
