# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Documents/OptionMessage.proto',
  package='',
  serialized_pb='\n\x1d\x44ocuments/OptionMessage.proto\"R\n\x13OptionMessageEntity\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x0f\n\x07sensors\x18\x03 \x02(\x05\x12\x10\n\x08\x63ommands\x18\x04 \x02(\x05')




_OPTIONMESSAGEENTITY = _descriptor.Descriptor(
  name='OptionMessageEntity',
  full_name='OptionMessageEntity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='OptionMessageEntity.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='OptionMessageEntity.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sensors', full_name='OptionMessageEntity.sensors', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='commands', full_name='OptionMessageEntity.commands', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=33,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['OptionMessageEntity'] = _OPTIONMESSAGEENTITY

class OptionMessageEntity(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _OPTIONMESSAGEENTITY

  # @@protoc_insertion_point(class_scope:OptionMessageEntity)


# @@protoc_insertion_point(module_scope)
